#' Creates the map section of a BEAST2 XML parameter file
#' @inheritParams create_beast2_input
#' @export
create_beast2_input_init <- function(
  ids,
  initial_phylogeny
) {
  text <- NULL
  # From https://www.beast2.org/fix-starting-tree/:
  #
  # if there is an initaliser generated by BEAUti of the form
  #
  #   <init estimate="false" id="RandomTree.t:xxx" initial="@Tree.t:xxx"
  #     spec="beast.evolution.tree.RandomTree" taxa="@xxx">
  #   </init>
  #
  # remove this element from the file, otherwise the tree will be Newick tree
  #   will be overwritten by a random tree.
  #
  # In other words: bluntly remove it
  if (!ribir::is_phylogeny(initial_phylogeny)) {
    text <- c(text, paste0("    <init id=\"RandomTree.t:", ids,
      "\" spec=\"beast.evolution.tree.RandomTree\" estimate=\"false\"",
      " initial=\"@Tree.t:", ids, "\" taxa=\"@", ids, "\">"
    ))
    text <- c(text, paste0(
      "        <populationModel id=\"ConstantPopulation0.t:",
      ids, "\" spec=\"ConstantPopulation\">"))
    text <- c(text, paste0("            <parameter id=\"randomPopSize.t:",
      ids, "\" name=\"popSize\">1.0</parameter>"))
    text <- c(text, "        </populationModel>")
    text <- c(text, "    </init>")
  } else {
    # Do not put initial tree here, but at the state section
  }
  text
}
