name: Build Singularity container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_singularity:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        singularity_version:
          - '3.8.1'
    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:

      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Show singularity version
        run: singularity version

      - name: Build container
        run: ./scripts/build_singularity_container.sh

      - name: Test container
        run: singularity test beautier.sif

      - name: Show help of container
        run: singularity run-help beautier.sif

      - name: Run container
        run: ./scripts/run_container.sh

