# Experimental!
#
# Build a Docker script and container, 
# from the Singularity script. 
# The Docker container is not tested

on:
  push:
  pull_request:

name: build_docker

jobs:
  build_singularity:

    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Show singularity version
        run: singularity version

      - name: Build container
        run: ./scripts/build_docker_container.sh

