on:
  push:
    paths:
      - README.md
      - 'docs/**'
      - .github/workflows/check_links.yaml
      - mlc_config.json
  pull_request:
    paths:
      - README.md
      - 'docs/**'
      - .github/workflows/check_links.yaml
      - mlc_config.json
  schedule:
  - cron: "0 0 12 * *"

name: check_links

jobs:
  check_links:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: 'mlc_config.json'

